//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AECEM.DALEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AECEventManagementEntities : DbContext
    {
        public AECEventManagementEntities()
            : base("name=AECEventManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventPit> EventPits { get; set; }
        public virtual DbSet<EventTeam> EventTeams { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<PitStop> PitStops { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamParticipant> TeamParticipants { get; set; }
    }
}
